name: Fesadyab CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Fesadyab/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Fesadyab/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Fesadyab with Maven
      working-directory: ./Fesadyab
      run: mvn test
